import { z } from 'zod';
import type { McpAuthContext } from '../auth/entra.js';
import {
  createReadOnlyTenantCosmos,
  type ReadOnlyTenantCosmos,
} from '../lib/cosmos.js';

export type ToolContext = McpAuthContext & { cosmos: ReadOnlyTenantCosmos };

export type ToolDef = {
  name: string;
  description: string;
  inputSchema: z.ZodObject<z.ZodRawShape>;
  execute: (args: Record<string, unknown>, ctx: ToolContext) => Promise<unknown>;
};

const queryOrders: ToolDef = {
  name: 'queryOrders',
  description: `List business outsourcing orders with optional filters.
Use this when the accountant asks about specific orders by month, worker, status,
or amount range (e.g., "Show me April orders for Sato", "Which orders are settled?").
Do NOT use this for monthly aggregated totals — use 'getMonthlyTotals' instead.
Read-only. Returns up to 200 orders matching the filters, sorted by createdAt DESC.`,
  inputSchema: z.object({
    yearMonth: z
      .string()
      .regex(/^\d{4}-\d{2}$/)
      .optional()
      .describe('e.g. "2026-04"'),
    workerGithubLogin: z.string().optional(),
    status: z.string().optional(),
    minAmountJpyc: z.number().int().optional(),
    maxAmountJpyc: z.number().int().optional(),
    limit: z.number().int().min(1).max(200).default(50),
  }),
  async execute(args, ctx) {
    return ctx.cosmos.listOrders({
      yearMonth: args.yearMonth as string | undefined,
      workerGithubLogin: args.workerGithubLogin as string | undefined,
      status: args.status as string | undefined,
      minAmountJpyc: args.minAmountJpyc as number | undefined,
      maxAmountJpyc: args.maxAmountJpyc as number | undefined,
      limit: (args.limit as number) ?? 50,
    });
  },
};

const getJournalEntries: ToolDef = {
  name: 'getJournalEntries',
  description: `Retrieve journal entries (仕訳) generated by the Bookkeeping Agent for a given month.
Use this when the accountant needs to verify or export entries to their accounting software.
Read-only. Returns one entry per bookkept order in the requested month.`,
  inputSchema: z.object({
    yearMonth: z.string().regex(/^\d{4}-\d{2}$/),
    workerGithubLogin: z.string().optional(),
  }),
  async execute(args, ctx) {
    const orders = await ctx.cosmos.listOrders({
      yearMonth: args.yearMonth as string,
      workerGithubLogin: args.workerGithubLogin as string | undefined,
      status: 'bookkept',
      limit: 200,
    });
    return orders
      .filter((o) => o.bookkeepingArtifacts)
      .map((o) => ({
        orderId: o.id,
        journal: o.bookkeepingArtifacts!.journalEntry,
        amountJpyc: o.amountJpyc,
        worker: o.workerGithubLogin,
      }));
  },
};

const getWithholdingReport: ToolDef = {
  name: 'getWithholdingReport',
  description: `Generate a withholding tax report for a specific worker over a year.
The Bookkeeping Agent has already classified each payment; this tool aggregates
the existing classifications. For ambiguous classifications it returns
"see tax accountant" markers.`,
  inputSchema: z.object({
    workerGithubLogin: z.string(),
    year: z.number().int().min(2000).max(2100),
  }),
  async execute(args, ctx) {
    const ym = `${args.year}`;
    const orders = await ctx.cosmos.listOrders({
      workerGithubLogin: args.workerGithubLogin as string,
      limit: 500,
    });
    const inYear = orders.filter((o) => o.createdAt.startsWith(ym));
    let appliedCount = 0;
    let appliedJpyc = 0;
    let notAppliedCount = 0;
    let notAppliedJpyc = 0;
    const needsReview: string[] = [];
    for (const o of inYear) {
      const w = o.bookkeepingArtifacts?.withholding;
      if (!w) continue;
      if (w.applies) {
        appliedCount++;
        appliedJpyc += w.amountJpyc ?? 0;
      } else {
        notAppliedCount++;
        notAppliedJpyc += o.amountJpyc;
      }
      if (o.bookkeepingArtifacts?.needsHumanReview) {
        needsReview.push(o.id);
      }
    }
    const accounts = await ctx.cosmos.listAllAccounts();
    const acct = accounts.find(
      (a) => a.worker?.githubLogin === args.workerGithubLogin,
    );
    return {
      worker: {
        githubLogin: args.workerGithubLogin,
        displayName: acct?.displayName ?? String(args.workerGithubLogin),
        wallet: acct?.worker?.wallet ?? '',
      },
      year: args.year,
      totalPaymentsJpyc: inYear.reduce((s, o) => s + o.amountJpyc, 0),
      withholdingApplied: { count: appliedCount, totalJpyc: appliedJpyc },
      withholdingNotApplied: {
        count: notAppliedCount,
        totalJpyc: notAppliedJpyc,
      },
      needsTaxAccountantReview: {
        count: needsReview.length,
        orderIds: needsReview,
      },
      rationale:
        needsReview.length > 0
          ? '一部の判定に税理士確認推奨マーカーがあります。'
          : '判定はすべて自動完結しています。',
    };
  },
};

const exportPaymentStatement: ToolDef = {
  name: 'exportPaymentStatement',
  description: `Get the payment statement (支払調書テンプレ) Markdown for a specific order.
The Bookkeeping Agent generates this template; this tool just retrieves it.
The template still requires human review before submission to tax authorities.`,
  inputSchema: z.object({
    orderId: z.string().uuid(),
  }),
  async execute(args, ctx) {
    const order = await ctx.cosmos.getOrder(args.orderId as string);
    if (!order || !order.bookkeepingArtifacts) {
      throw new Error('not_found_or_not_bookkept');
    }
    return {
      orderId: order.id,
      paymentStatementMarkdown: order.bookkeepingArtifacts.paymentStatementMarkdown,
      generatedAt: order.bookkeepingArtifacts.generatedAt,
      needsHumanReview: order.bookkeepingArtifacts.needsHumanReview,
    };
  },
};

const getMonthlyTotals: ToolDef = {
  name: 'getMonthlyTotals',
  description: `Aggregate total business outsourcing payments for a given month.
Use this for high-level accounting review questions like
"how much did we spend on outsourcing in April?".
For per-order detail use 'queryOrders'.`,
  inputSchema: z.object({
    yearMonth: z.string().regex(/^\d{4}-\d{2}$/),
  }),
  async execute(args, ctx) {
    const orders = await ctx.cosmos.listOrders({
      yearMonth: args.yearMonth as string,
      limit: 500,
    });
    const byWorkerMap = new Map<
      string,
      { worker: string; orders: number; amountJpyc: number }
    >();
    const byStatusMap = new Map<string, number>();
    let total = 0;
    for (const o of orders) {
      total += o.amountJpyc;
      const w = byWorkerMap.get(o.workerGithubLogin) ?? {
        worker: o.workerGithubLogin,
        orders: 0,
        amountJpyc: 0,
      };
      w.orders++;
      w.amountJpyc += o.amountJpyc;
      byWorkerMap.set(o.workerGithubLogin, w);
      byStatusMap.set(o.status, (byStatusMap.get(o.status) ?? 0) + 1);
    }
    return {
      yearMonth: args.yearMonth,
      totalOrders: orders.length,
      totalAmountJpyc: total,
      byWorker: [...byWorkerMap.values()].sort(
        (a, b) => b.amountJpyc - a.amountJpyc,
      ),
      byStatus: [...byStatusMap.entries()].map(([status, count]) => ({
        status,
        count,
      })),
    };
  },
};

export const tools: Record<string, ToolDef> = {
  queryOrders,
  getJournalEntries,
  getWithholdingReport,
  exportPaymentStatement,
  getMonthlyTotals,
};

export function buildToolContext(auth: McpAuthContext): ToolContext {
  return {
    ...auth,
    cosmos: createReadOnlyTenantCosmos(auth.tenantId),
  };
}
